//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 11:53:11 PM GMT 
//


package realtreade.tradeengine;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the realtreade.tradeengine package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: realtreade.tradeengine
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTradeResponse }
     * 
     */
    public GetTradeResponse createGetTradeResponse() {
        return new GetTradeResponse();
    }

    /**
     * Create an instance of {@link GetTradeRequest }
     * 
     */
    public GetTradeRequest createGetTradeRequest() {
        return new GetTradeRequest();
    }

    /**
     * Create an instance of {@link Trade }
     * 
     */
    public Trade createTrade() {
        return new Trade();
    }

}
