//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 11:53:11 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://realtreade/tradeengine", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package realtreade.tradeengine;
